# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_X7my_5WGCrgB-UCtKum6CUd-5GPgnbz
"""


import pandas as pd
import numpy as np

df1 = pd.read_csv("predsJason.csv")
df2 = pd.read_csv("predsJason2.csv")

DataJason1 = pd.DataFrame(df1,columns= ['DATA1', 'DATA2'])

DataJason2 = pd.DataFrame(df2,columns= ['DATA1', 'DATA2'])

df1['DATA2'] = df2['DATA2']

df1['Datanya Sama ?'] = np.where(df1['DATA1'] == df2['DATA1'], 'True', 'False')
df1['Perbedaan Angkanya ?'] = np.where(df1['DATA1'] == df2['DATA1'], 0, df1['DATA1'] - df2['DATA2'])

print (df1)